name: Deploy Shopify Theme

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install Dependencies (Ruby, Shopify CLI, jq)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ruby-full jq
          sudo gem install bundler
          npm install -g @shopify/cli@3.70.0
          npm install

      - name: Build Theme
        run: npm run build

      - name: Push Theme to Shopify
        env:
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        run: |
          shopify theme push \
            --live \
            --json \
            --theme $SHOPIFY_THEME_ID \
            --store $SHOPIFY_STORE \
            --password $SHOPIFY_PASSWORD